version: '3.7'
services:
  app:
    build: 
      context: .
      dockerfile: .docker/Dockerfile
    image: 'achievement'
    ports:
      - 8080:80
    volumes: 
      - ./:/var/www/html:delegated
  db:
    image: mysql:5.6
    restart: always
    ports: 
      - "3306:3306"
    environment: 
      MYSQL_DATABASE: achievement
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_ROOT_PASSWORD: ""
    volumes:
      - ./mysql5.6:/var/lib/mysql5.6:delegated
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_USER: root
      PMA_PASSWORD: ""
      PMA_ARBITRARY: 1
      PMA_HOST: db
    links:
      - db
    ports:
        - 8000:80
    volumes:
        - ./phpmyadmin/sessions:/sessions:delegated
